version: '3.9'
networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin:

services:
  aspnet-api:
    container_name: api
    build:
      context: ./v1
      dockerfile: ./Dockerfile
    depends_on:
    - "postgres_db"
    environment:
      - ConnectionStrings__PersonDbConnection=User Id=postgres; Password=123;Server=postgres_db;Port=5432;Database=users; IntegratedSecurity=true;
    ports: 
      - "8088:80"
    networks:
      - postgres
    
   

  postgres_db:
    container_name: postgres_container
    image: postgres:13.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=users
      - PGDATA=/data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - postgres
    
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin

    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped


